add_newline = false
format = """ 
$hostname$directory$git_branch$git_status$php$rust$golang$nix_shell
$linebreak$character
"""
command_timeout = 2000

[directory]
format = "[  ](bold grey)[$path ](blue)[$read_only|]($read_only_style silver) "
truncation_length = 2
home_symbol = " 󱄫 "

[character]
success_symbol = "[󰔷 ](green)"
error_symbol = "[󰔶 ](red)"
vicmd_symbol = "[ ](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch ](pink)"
# ~/.config/starship.toml

[git_status]
conflicted = ' 󰈿 '
up_to_date = ' ✓ '
untracked = ' 󰃹 '
stashed = ' 󰩪 '
modified = ' 󰷥 '
staged = ' [++\($count\)](green)'
renamed = ' 󰮆 '
ahead = '⇡ $count '
diverged = ' ⇕⇡ $ahead_count -⇣ $behind_count '
behind = ' ⇣ $count'
style = 'bold yellow'

[nix_shell]
symbol = "  "
[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:purple)]($style)'
[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:olive)]($style)'
[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:blue)]($style)'
[c]
format = '[[ $symbol ($version) ](fg:olive)]($style)'
symbol = ""
detect_file = ['Makefile']
commands = [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ], ['zig','cc','--version'] ]
disabled = false
[zig]
symbol = ""
detect_file = ['build.zig.zon']
format = '[[ $symbol ($version) ](fg:yellow)]($style)'
