#!/usr/bin/env bash

FILE_NAME="$1"
MODE="$2"
CHK="$3"
FN="$4"

# Rename and move
FILE_FN="${FILE_NAME}_fn.json"
FILE_SMT="${FILE_NAME}.smt2"
FILE_JSON="${FILE_NAME}.json"


if [ "${MODE}" == "--meta" ]; then
	echo "Generating Bosque Metadata..."

	if [ "${CHK}" == "--test" ]; then
		FILE_PATH=$(pwd)/$FILE_NAME.bsq
		FILE_TEST=$(pwd)/$FILE_NAME.bsqtest

		# Get BSQON
		/usr/bin/node ~/work/BosqueCore/bin/src/cmd/bosque.js --function $FN $FILE_PATH $FILE_TEST
		/usr/bin/node ~/work/BosqueCore/bin/src/cmd/analyze.js $FILE_PATH $FILE_TEST
	else
		FILE_PATH=$(pwd)/$FILE_NAME.bsq
		# Get BSQON
		/usr/bin/node ~/work/BosqueCore/bin/src/cmd/bosque.js --function $FN $FILE_PATH
		# Get SMT
		/usr/bin/node ~/work/BosqueCore/bin/src/cmd/analyze.js $FILE_PATH 
	fi


	# Rename and move
	FILE_FN=$1_fn
	mv $(pwd)/jsout/typeinfo.json $(pwd)/$FILE_NAME.json
	mv $(pwd)/jsout/targettype.json $(pwd)/$FILE_FN.json
	mv $(pwd)/smtout/formula.smt2 $(pwd)/$FILE_NAME.smt2

	#
	rm -r $(pwd)/jsout/
	rm -r $(pwd)/smtout/
else
	time ./output/smtextract $FILE_SMT $FILE_FN $FILE_JSON $MODE
fi


