#!/usr/bin/env bash

# read -p "BSQ File: " file

FILE_NAME=$1
FILE_PATH=$(pwd)/$FILE_NAME.bsq

echo FILEPATH: $FILE_PATH


# # Get SMT
/usr/bin/node /home/kennett/work/BosqueCore/bin/src/cmd/analyze.js $FILE_PATH
# Get BSQON
/usr/bin/node /home/kennett/work/BosqueCore/bin/src/cmd/bosque.js --function main $FILE_PATH


# Rename and move
FILE_FN=$1_fn
mv $(pwd)/jsout/typeinfo.json $(pwd)/$FILE_NAME.json
mv $(pwd)/jsout/targettype.json $(pwd)/$FILE_FN.json
mv $(pwd)/smtout/formula.smt2 $(pwd)/$FILE_NAME.smt2

#
rm -r $(pwd)/jsout/
rm -r $(pwd)/smtout/
