#!/usr/bin/env bash


# pipewire-pulse &
# sleep 1

swww-daemon &
sleep 1 

swww img ./Pictures/wallpapers/Trandheim.jpg --transition-type=grow &
sleep 1


gammastep &
sleep 1

openrgb -c 9F1C02
sleep 1

wlr-randr --output DP-2 --custom-mode 3440x1440@165.00

sleep 1
syncthing &
