#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/notes/Resources -type f | fzf --border-label=Zathura-Picker)
fi

if [[ -z $selected ]]; then
	exit 0
fi

zathura $selected
